name: AntiBotFilter
version: '${project.version}'
main: com.reformer.antibotfilter.AntiBotFilter
api-version: 1.17
authors:
  - AmazinAmazon
  - Vertixx
description: Simple verification system plugin

