name: AntiBotFilter
version: '${project.version}'
main: com.reformer.antibotfilter.AntiBotFilter
api-version: 1.17
commands:
  blacklistip:
    description: Allows you to blacklist a IP.
    usage: /<command> <IP>
  whitelistip:
    description: Allows you to remove a blacklisted IP.
    usage: /<command> <IP>
