name: AntiBotFilter
version: '${project.version}'
main: com.reformer.antibotfilter.AntiBotFilter
api-version: 1.16
authors:
  - AmazinAmazon
  - Vertixx
description: Simple verification system plugin
commands:
  verify:
    description: Forces a player to verify
    usage: /<command> <player>
